import Foundation

/// Pure classification rules. Everything here must stay deterministic and testable:
/// evidence in, verdict out, no filesystem access.
public enum Classifier {

    public static func classify(_ item: ScanItem, now: Date = .now) -> (Safety, [String]) {
        if let worktree = item.worktree {
            return classifyWorktree(item, worktree, now: now)
        }
        return classifyNonWorktree(item, now: now)
    }

    static func classifyWorktree(_ item: ScanItem, _ tree: WorktreeState, now: Date) -> (Safety, [String]) {
        var reasons: [String] = []

        if tree.isMainWorktree {
            return (.protected, ["This is the main worktree of its repository."])
        }
        if item.hasActiveProcess {
            reasons.append("A running process is using this worktree.")
        }
        if item.hasActiveSession {
            reasons.append("An agent session using this worktree appears active.")
        }
        if !reasons.isEmpty {
            return (.protected, reasons)
        }
        if tree.isLocked {
            return (.protected, ["The worktree is locked in git (git worktree lock)."])
        }

        if tree.hasModifiedFiles {
            reasons.append("Uncommitted changes to tracked files.")
        }
        if tree.hasUntrackedFiles {
            reasons.append("Untracked files that exist nowhere else.")
        }
        switch tree.unpushedCommits {
        case .some(let n) where n > 0:
            reasons.append("\(n) commit\(n == 1 ? " exists" : "s exist") only on this machine.")
        case .none:
            reasons.append("Could not determine whether commits are pushed.")
        default:
            break
        }
        if !tree.isRegistered {
            reasons.append("Not registered with its git repository (orphaned worktree directory).")
        }
        if !reasons.isEmpty {
            // Unpushed work or dirty state is reviewable, never silently deletable.
            return tree.unpushedCommits == nil && !tree.hasModifiedFiles && !tree.hasUntrackedFiles
                ? (.unknown, reasons)
                : (.review, reasons)
        }

        reasons.append("Clean working tree, no untracked files, all commits are on a remote.")
        if let last = item.lastActivity {
            let days = Int(now.timeIntervalSince(last) / 86_400)
            reasons.append(days == 0 ? "Last activity today." : "Last activity \(days) day\(days == 1 ? "" : "s") ago.")
        }
        return (.safe, reasons)
    }

    static func classifyNonWorktree(_ item: ScanItem, now: Date) -> (Safety, [String]) {
        if item.hasActiveProcess {
            return (.protected, ["A running process is using this data."])
        }
        if item.hasActiveSession {
            return (.protected, ["An active agent session is using this data."])
        }

        switch item.category {
        case .nodeModules:
            return (.safe, ["node_modules is fully regenerated by the package manager on install."])
        case .packageCache:
            return (.safe, ["Package caches only speed up future installs; contents are re-downloaded on demand."])
        case .derivedData:
            return (.safe, ["Derived data is rebuilt by Xcode on the next build."])
        case .toolCache:
            return (.safe, ["Cache data the tool recreates automatically."])
        case .archives:
            return (.review, ["Archives contain built releases and their debug symbols; they cannot be regenerated for past builds."])
        case .deviceSupport:
            return (.review, ["Device support files are re-downloaded when the device is next connected."])
        case .simulators:
            return (.review, ["Simulator data may include app containers you still use."])
        case .toolSessions:
            return (.review, ["Session history may hold context you want to keep; it is not needed for the tool to run."])
        case .worktree:
            return (.unknown, ["Worktree state could not be inspected."])
        }
    }
}
