import Foundation

/// Finds node_modules and per-project framework build caches (.next, .nuxt,
/// cargo target, …) under the configured project roots.
public struct NodeModulesScanner: StorageScanner {
    public let name = "node_modules"
    public var maxDepth: Int

    public init(maxDepth: Int = 5) {
        self.maxDepth = maxDepth
    }

    /// Directory name → tool + human title. All are regenerated by a build.
    static let buildDirectories: [String: (tool: Tool, title: String)] = [
        ".next": (.npm, "Next.js build cache"),
        ".nuxt": (.npm, "Nuxt build cache"),
        ".turbo": (.npm, "Turborepo cache"),
        ".svelte-kit": (.npm, "SvelteKit build cache"),
        ".parcel-cache": (.npm, "Parcel cache"),
        ".angular": (.npm, "Angular build cache"),
        ".output": (.npm, "Nitro build output"),
    ]

    public func scan(context: ScanContext) async throws -> [ScanItem] {
        var nodeModules: [URL] = []
        var buildCaches: [(URL, Tool, String)] = []
        for root in context.projectRoots where context.fileManager.directoryExists(root) {
            try search(root, depth: 0, nodeModules: &nodeModules, buildCaches: &buildCaches)
        }

        var items: [ScanItem] = []
        for url in nodeModules {
            try Task.checkCancellation()
            let project = url.deletingLastPathComponent()
            var item = ScanItem(
                path: url.path,
                displayName: project.lastPathComponent,
                tool: .npm,
                category: .nodeModules,
                lastActivity: latestModification(in: project, maxDepth: 1),
                hasActiveProcess: context.processes.referencesPath(project.path)
            )
            (item.safety, item.reasons) = Classifier.classify(item)
            items.append(item)
        }
        for (url, tool, title) in buildCaches {
            try Task.checkCancellation()
            let project = url.deletingLastPathComponent()
            var item = ScanItem(
                path: url.path,
                displayName: "\(project.lastPathComponent): \(title)",
                tool: tool,
                category: .buildCache,
                // The cache's own mtime says when the project was last built or
                // its dev server last ran — the staleness signal that matters.
                lastActivity: latestModification(in: url, maxDepth: 0),
                hasActiveProcess: context.processes.referencesPath(url.path)
                    || context.processes.referencesPath(project.path)
            )
            (item.safety, item.reasons) = Classifier.classify(item)
            items.append(item)
        }
        return items
    }

    private func search(
        _ url: URL, depth: Int,
        nodeModules: inout [URL],
        buildCaches: inout [(URL, Tool, String)]
    ) throws {
        try Task.checkCancellation()
        for child in FileManager.default.contentsOfDirectoryIfPresent(url, includeHidden: true) {
            guard (try? child.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory == true else { continue }
            let name = child.lastPathComponent
            if name == "node_modules" {
                nodeModules.append(child)  // never descend into one
            } else if let match = Self.buildDirectories[name] {
                buildCaches.append((child, match.tool, match.title))
            } else if name == "target",
                      FileManager.default.fileExists(atPath: url.appendingPathComponent("Cargo.toml").path) {
                buildCaches.append((child, .rust, "Cargo target"))
            } else if name.hasPrefix(".") {
                // Hidden dirs are tool internals; .claude/worktrees is handled
                // by the worktree scanner so its contents aren't double-counted.
                continue
            } else if depth < maxDepth {
                try search(child, depth: depth + 1, nodeModules: &nodeModules, buildCaches: &buildCaches)
            }
        }
    }
}
